### ISSUE TITLE
PackagingResults: Error

### ISSUE THREAD

**Issue by ranger0201** [hugoattal/ElectronicNodes#60] opened 2022-07-01 05:58 UTC
**Describe the bug**

I got a build error when compiling and launching my level.
I got a build error when compiling and launching my level. I noticed that I had previously installed a new “Electronic Nodes
&Darker Nodes.”. After disabling it, the error disappeared.

P.S : Problem occurs with Electronic Nodes and no problem with Darker Nodes.

**To Reproduce**
1. Create New Empty Project
2. PlugIn Load
3. Project Run

<The error contents are as follows.>

PackagingResults: Error: Launch failed! Missing UE4Game binary.
You may have to build the UE4 project with your IDE. Alternatively, build using UnrealBuildTool with the commandline:
UE4Game <Platform> <Configuration>

**Environment (please complete the following information):**
 - Unreal Engine version: 4.27.2
 - Operating System: Windows 10 64bits

**Comment by hugoattal** [comment] 2022-07-04 10:34
Hum, I tried to reproduce, but couldn't get the error... Here's what I did:

- Open 4.27.2 engine
- Create new project (FPS / Blueprint)
- Activate Electronic Nodes (v3.5)
- Retard the project
- Package for Windows 64 bits

Here's the result:
![image](https://user-images.githubusercontent.com/4563971/177137245-4fc73ccf-8800-4ece-959b-0bf0c462c88d.png)

Maybe I'm missing something, could please zip an example project with the error?
Or you can try to past me the whole output log, maybe there's something useful there.

**Comment by ranger0201** [comment] 2022-07-05 03:43
Hello, I just made a new project(ThirdPerson) and tested it, and the results are the same. I want to send a blank computer-generated project, but there is no way to share it because the base capacity is 1GB.

**Comment by ranger0201** [comment] 2022-07-07 01:49
Thanks for the reply.
This error does not appear in the dark node. Appears only on electronic nodes.
My position is an artist, so the company does not allow me that Install to visual studio. I can't use it until this issue is resolved.
Anyway, I hope it will be resolved someday. Good Luck !!! ^^;;;

**Comment by hugoattal** [comment] 2022-07-07 11:19
Hum, I get that's not the right solution for you then...

After a bit more digging, it appears that it's because Electronic Nodes requires the Control Rig plugin (to update the Control Rig schemas). And the Control Rig plugin needs Visual Studio to compile properly (for whatever reason).

The fact the Electronic needs to be compiled at all is an Unreal bug: the plugin is marked as Editor Only and should not do anything with packaging.

So, I'm a bit stuck here:
- Either I solve your problem by removing the Control Rig compatibility and others lose the ability to use EN in Control Rig
- Or I let the Control Rig compatibility, but you can't use EN

What I can do is create a special version of Electronic Nodes without the Control Rig, just for you, but you'll need to install EN in your project plugins folder. Would that be a good solution?

**Comment by ranger0201** [comment] 2022-07-11 07:32
HI ^^
I am sorry about the late reply. 
First of all, I decided to move on to a very simple way of not using Electronic Nodes. 
If the work is busy and the solution is not simple, it will be a problem again someday. 
The ongoing team project will be updated to Unreal version 5 at some point. At that point, I think I'll have to look at the compatibility again and use it. 
I bought a China PlugIn called Node Graph Assistant and am using it temporarily. 
I will give you feedback again when the project moves to Unreal 5.
God Bless You !!!

**Closed** 2023-05-11 20:26 UTC
Labels: bug, pending
