### ISSUE TITLE
Node link highlighting does not work when plugin is enabled but not activated

### ISSUE THREAD

**Issue by teknomaniac** [hugoattal/ElectronicNodes#58] opened 2022-04-15 01:11 UTC
When the plugin is enabled but not activated, node links do not get highlighted when moused over. Only the node pin the mouse is closer to along the link gets lit up.

![node_link_highlight](https://user-images.githubusercontent.com/40051909/163499807-0bbd0ed2-7098-4ead-9036-495a34a47004.png)

**To Reproduce**
1. Install the plugin to a new project.
2. Go to Edit > Editor Preferences... > Electronic Nodes Plugin > Uncheck `Master Activate`.
3. Restart the editor.
4. Create or open an existing Blueprint, and connect two nodes to one another.
5. Mouse over the link between these two nodes and notice no highlighting.

**Expected behavior**
When you mouse over the link between two nodes, the link should be highlighted while all other links in the Blueprint are dimmed. This is default Unreal Blueprint Editor behavior.

**Screenshots**
The screenshot above illustrates the bug behavior. Here's a screenshot of expected behavior for comparison:

![node_link_highlight_expected](https://user-images.githubusercontent.com/40051909/163501546-49fbd3ec-e2f4-4d97-b342-616c09f406d2.png)

**Environment (please complete the following information):**
 - Unreal Engine: 4.27.2
 - Plugin version: 3.5
 - Operating System: Windows 64bits

**Additional context**
The workaround presented in [https://github.com/hugoattal/ElectronicNodes/issues/52](url) to enable `Master Activate`, disable `Use Hot Patch`, then disable `Master Activate` again gave the correct results seen in the screenshot above. So I believe that the fix to issue 52 should hopefully also resolve this. :)

**Comment by hugoattal** [comment] 2022-04-15 10:00
Sorry for this, try disabling the "Hot Patch" feature in the configuration panel. This is still a bug, but it should be fixed temporary by doing this.

**Comment by hugoattal** [comment] 2022-04-15 12:41
duplicate of https://github.com/hugoattal/ElectronicNodes/issues/52

**Comment by hugoattal** [comment] 2022-04-18 17:23
Fixed by 3.6

**Closed by hugoattal** 2022-04-18 17:23 UTC
Labels: bug, ready
